// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojzrvbftbfpyywhhsdyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qenJ2YmZ0YmZweXl3aGhzZHlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NDcxNDIsImV4cCI6MjA3MTMyMzE0Mn0.0qmAFVYlvsRFP6WYHNIWrrseyP8KurqWxeBrUaD-DDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});